CREATE TABLE IF NOT EXISTS PRODUCTS (
    VEHICLE_ID TEXT,
    VEHICLE_NAME TEXT,
    COMPANY_NAME TEXT,
    VEHICLE_ENGINE TEXT,
    PRICE REAL
);

INSERT INTO PRODUCTS (VEHICLE_ID TEXT,VEHICLE_NAME TEXT,COMPANY_NAME TEXT,VEHICLE_ENGINE TEXT,) VALUES
    ('1', 'Bugatti Chiron', 'BUGATTI', 'W16', '₹28.40 crore')